In [22]:
import numpy as np 


In [23]:
import pandas as pd

function

In [24]:
def student_info(name,age=18):
    print(name,age)

function definition

function calling

In [25]:
student_info("john")
student_info("alice",22)

john 18
alice 22


NUMPY


installing numpy " pip install numpy"

import numpy as np

creating 1-d array

In [26]:
x=np.array([1,2,3,4,5])

creating 2-d array

In [27]:
y=np.array([[1,2],[3,4],[5,6]])

creating 3d array

In [28]:
z=np.array([[[1,2],[3,4]],[[5,6],[6,7]]])

In [29]:
print(x)
print(y)
print(z)

[1 2 3 4 5]
[[1 2]
 [3 4]
 [5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [6 7]]]


PANDAS



pip install pandas

import pandas as pd ,
1d data -> series ,/n
2d data -> dataframe

create a pandas series from a list

create a pandas dataframe from a dictionary

In [30]:
s=pd.Series([10,20,30],
            name="mynumbers")
print(f"pandas series:\n{s}")
print(f"types of series:{type(s)}")

pandas series:
0    10
1    20
2    30
Name: mynumbers, dtype: int64
types of series:<class 'pandas.core.series.Series'>


In [31]:
data={
    'name':['alice','bob','charlie'],
    'age':[25,30,35],
    'city':['new york','london','paris'],
    'salary':[7000,8000,10000]
}
df=pd.DataFrame(data)
print(f"\npandas DataFrame:\n{df}")



pandas DataFrame:
      name  age      city  salary
0    alice   25  new york    7000
1      bob   30    london    8000
2  charlie   35     paris   10000


In [32]:
data={
    'name':['alice','bob','charlie'],
    'age':[25,30,35],
    'city':['new york','london','paris'],
    'salary':[7000,8000,10000]
}

In [33]:
df=pd.DataFrame(data)
print(f"\npandas DataFrame:\n{df}")


pandas DataFrame:
      name  age      city  salary
0    alice   25  new york    7000
1      bob   30    london    8000
2  charlie   35     paris   10000


analysising public available data

In [42]:
df=pd.read_csv("D:\Shantanu Swaraj\python_basic\former_names.csv")
#read_csv xlsx
#df = pd.DataFrame()
#df.head()


<>:1: SyntaxWarning: invalid escape sequence '\S'
<>:1: SyntaxWarning: invalid escape sequence '\S'
C:\Users\HP\AppData\Local\Temp\ipykernel_17876\557496978.py:1: SyntaxWarning: invalid escape sequence '\S'
  df=pd.read_csv("D:\Shantanu Swaraj\python_basic\former_names.csv")


OSError: [Errno 22] Invalid argument: 'D:\\Shantanu Swaraj\\python_basic\x0cormer_names.csv'

In [43]:
df.head()

name  age      city  salary
0    alice   25  new york    7000
1      bob   30    london    8000
2  charlie   35     paris   10000