assignment day 3


ASSIGNMENT 3  {using numpy an pandas create a small dataanalysis script}

In [3]:
import numpy as np
import pandas as pd

In [11]:
y=np.array([[1,2,3],[3,4,5],[5,6,7]])

baic array print

In [12]:
print(y)

[[1 2 3]
 [3 4 5]
 [5 6 7]]


In [16]:
y= y*2

new array

In [17]:
print(y)

[[ 2  4  6]
 [ 6  8 10]
 [10 12 14]]


section 2 : dataframe

In [49]:
import pandas as pd
data={
    'product_name':['a','b','c'],
    'price':['10','20','30'],
    'stock_quantity':[100,200,50]
}
df=pd.DataFrame(data)
print(f"\npandas DataFrame:\n{df}")


pandas DataFrame:
  product_name price  stock_quantity
0            a    10             100
1            b    20             200
2            c    30              50


section 3 : filtering the data

In [48]:
df=pd.DataFrame(data)

newdf=df[df['stock_quantity']>50]
#df=pd.DataFrame(newdf)
#newdf=df['stock_quantity']>50]
print(f"\npandas DataFrame:\n{newdf}")




pandas DataFrame:
  product_name price  stock_quantity
0            a    10             100
1            b    20             200
